---

repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: HEAD
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-mod-tidy
      - id: go-build
