sudo: required
language: go
go:
  - 1.13.x
  - 1.14.x
  - master

env:
  - GO111MODULE=on
services:
  - docker
before_script:
  - go get github.com/golangci/golangci-lint@v1.23.8
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
before_install:
  - docker-compose --version
  - docker-compose up -d
script:
  - make lint
  - make unittest
  - make benchtest
  - make build
  - make systest
after_success:
  - bash < (curl -s https://codecov.io/bash)
